# Generated by Django 6.1 on 2026-09-13 01:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
