# Generated by Django 6.1 on 2026-09-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.AddField(
            model_name='project',
            name='month_year',
            field=models.CharField(default='', max_length=31),
        ),
        migrations.AddField(
            model_name='project',
            name='pict',
            field=models.URLField(blank=True, null=True),
        ),
    ]
