# Generated by Django 6.1 on 2026-09-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='pict',
        ),
        migrations.AddField(
            model_name='achievement',
            name='achievement_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
