# Generated by Django 6.1 on 2026-09-13 01:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projects_alter_experience_ended_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('date', models.DateField(blank=True, default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
