# Generated by Django 6.1 on 2026-09-13 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_delete_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
    ]
