# Generated by Django 6.1 on 2026-09-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, default=''),
        ),
    ]
